version: '3'
services:
  kerberos-server:
    container_name: kerberos-server
    image: qcastel/kerberos-server
    build:
      context: server
      dockerfile: ./server/Dockerfile
    ports:
      - "6088:88"
    hostname: kdc.mykerberos.com
    volumes:
      - ./server/:/server
  kerberos-client:
    container_name: kerberos-client
    image: qcastel/kerberos-client
    build:
      context: client
      dockerfile: ./client/Dockerfile
    hostname: client.mykerberos.com
    volumes:
      - ./client/:/client
